name: school_cafteria
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter



  cupertino_icons: ^1.0.2
  flutter_bloc:
  dartz:
  equatable:
  get_it:
  internet_connection_checker:
  http:
  shared_preferences:
  dio:
  sizer:
  email_validator:
  fluttertoast:
  after_layout:
  grouped_list:
  flutter_multi_formatter:
  flutter_speed_dial:
  auto_size_text:
  image_picker:
  rename:
  simple_animations: ^3.0.0
  counter_button: ^1.0.1
  firebase_messaging: ^14.2.5
  firebase_core: ^2.7.0
  flutter_local_notifications:
  rxdart:
  dotted_line:
  device_preview:
  intl: ^0.17.0
  badges: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  fonts:
    - family: HELVE
      fonts:
        - asset: assets/fonts/helv/HELVETICANEUELTARABIC-LIGHT.TTF
          weight: 300
        - asset: assets/fonts/helv/HELVETICANEUELTARABIC-ROMAN.TTF
          weight: 400
        - asset: assets/fonts/helv/HELVETICANEUELTARABIC-BOLD.TTF
          weight: 500
  uses-material-design: true
  assets:
    - assets/images/
    - assets/launcher/
    - assets/lang/en.json
    - assets/lang/ar.json
